import GlobalProvider from "@/components/Application/GlobalProvider";
import "./globals.css";
import { Assistant } from "next/font/google";
import { ToastContainer } from "react-toastify";

const assistantfont = Assistant({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "E-Store Website ",
  description: "Generated by Jitendra chauhan",
  icons: {
    icon: '/assets/images/favicon.ico',
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${assistantfont.className} antialiased`}>
        <GlobalProvider>
          <ToastContainer />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
